name: Publish zip

on:
  release:
    types: [published]

jobs:
  publish-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PUBLISH_ZIP }}
          ref: master
          fetch-depth: 0

      - name: Zip integration
        run: |
          cd custom_components/fanpy
          zip -r "$GITHUB_WORKSPACE/fanpy.zip" ./
          echo "Zip created at $GITHUB_WORKSPACE/fanpy.zip"

      - name: Upload fanpy.zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: fanpy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_ZIP }}
